# Project:              Talisman
# Owning organization:  LES/DI/PUC-Rio
# Build: test strings

[Diretorios]

Nome        =  Tst-tim

PathDefault =  ..\sources
err         =  ..\sources
obj         =  ..\Obj
ferram      =  ..\..\tools\programs
cpp         =  ..\sources
hpp         =  ..\sources
inc         =  ..\tables;..\..\Global\Consts
str         =  ..\tables
table       =  ..\tables
makeup      =  ..\tables

[LimpaMais]
   del $(Fobj)\time.obj

[Modulos]
str_bcd.str     g
str_cnt.str     g
str_dis.str     g
str_dsp.str     g
str_env.str     g
str_exc.str     g
str_glb.str     g
str_global.str  g
str_log.str     g
str_msg.str     g
str_sio.str     g
str_sls.str     g
str_smt.str     g
str_str.str     g
str_tim.str     g
str_tst.str     g
str_ver.str     g

string.makeup   g

Time             /D_TEST_TIM
tst_tim 

BCDArit
breakpnt
Counters
Disaster
Dynspac
Environ
Exceptn
Global
GnrcTest
Int_Cnt         
Int_DSP
Logger
Main
Message
MsgBCD
Msgbin
Msgstr
MsgTime
ReadTest
Simplist
Sioctrl
Sls_Elem
String
SymbTab
Tracer
Verifier

# SPECTEST must contain the name of the module containing the specific test class 
# It will be used to generate an include file

[MacrosApos]
SPECTEST    = tst_tim      

[Link]
   SET CL=
   CD  $(Fobj)
   LINK  $(L)  @$(NOME).build >> $(Ferr)\$(NOME).err
   del $(Fobj)\time.obj

[BuildInicio]
/OUT:Tst-tim.EXE
/INCREMENTAL:NO
/MACHINE:IX86

[Fim]
