// Script:    Tst-main-08.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality

// Test throw, do not catch due to missing recovery command

//
// ==========>>> Must stop with 4 errors and disaster
//

== Declarations
=DeclareParameter  idAssert    int   154
=DeclareParameter  idEnforce   int   153
=DeclareParameter  typeAssert  int     1
=DeclareParameter  typeEnforce int     2
=DeclareParameter  typeError   int     3
=DeclareParameter  typeFailure int     4
=DeclareParameter  tstMessage  int   30147

=DeclareParameter  selectError   int     1
=DeclareParameter  selectFailure int     2

== Test missing program error exception catcher, blank line
=Throw              selectFailure   0  -1  "test"

=ExceptionProgram   typeError    tstMessage 'c'
// Should never reach this point

