// Script:    Tst-main-11.script
// Author:    Arndt von Staa
// Date:      22/jun/2012
// Purpose:   Test basic functionality, include file


== Declare open segment constants
=DeclareParameter  idAssert          int   144
=DeclareParameter  typeUsage         int     3

#include  "Tst-main-11"

== Declare existing parameter
=DeclareParameter  idAssert          int   144
=Recover
=DeclareParameter  idEnforce         int   143
=Recover
=DeclareParameter  OpenAnonym        int 1
=Recover

== included line 26: Test hexadecimal with coded characters, comparand shorter
=comparehex   "\xaA\xbB\xCc\xDd\xEE\xff" "AAbbCcDd"


// end of include file