// Script:    Tst-cnt-01.script
// Author:    Arndt von Staa
// Date:      27/jun/2017
// Purpose:   Test mutation test 

== Start measuring time
=StartClock  1

//
== Start mutation test
=Reset

//
== Test default idMutant == 0
=GetIdMutant     0
=MutationTest   20  8

//
== Test not existing mutant
=SetIdMutant     5
=MutationTest   20  8
=GetIdMutant     5

//
== Test existing mutant, must fail
=SetIdMutant    10
=MutationTest   20  8
=Recover

//
// does not fail because expected value has been set to be equal to wrong result
== Test existing mutant with large limit, 
=GetIdMutant    10
=MutationTest   83  3

//
== Test program limit with no mutant
=SetIdMutant    0
=MutationTest   83  23

//
== Test greater than program limit with no mutant
=MutationTest   84  23

//
== Test less than program limit with no mutant
=MutationTest   82  22

//
== Test few with mutant 11, should not fail
=SetIdMutant    11
=MutationTest   20   8

//
== Test program limit with mutant, should fail
=MutationTest   83  23
=Recover

//
== Test greater than program limit with mutant, should not fail
=MutationTest   84  23

//
== Test less than program limit with mutant, should not fail
=MutationTest   82  22

//
== Test smaller than low limit with no mutant, should not fail
=SetIdMutant     0
=MutationTest    2   3

//
== Test negative with no mutant, should not fail
=MutationTest   -2   3

//
== End measuring time
=DisplayElapsedTime      1
