// Script:    Tst-str-01.script
// Author:    Arndt von Staa
// Date:      28/ago/2007
// Purpose:   Test string, construct and assign operations

== Define counter files counters
=CounterDeleteAccumFile   "..\\Sources\\nstring.count"  // destrói acumulação caso haja, assegura 0
=CounterReadDeclaration   "..\\Sources\\nstring.cnt"    // lê definição de contadores
=CounterReadAccumFile     "..\\Sources\\nstring.count"  // registra arquivo de acumulação

== Declare constants
=DeclareParameter  Str1  int  1
=DeclareParameter  Str2  int  2
=DeclareParameter  Str3  int  3
=DeclareParameter  Str4  int  4
=DeclareParameter  Str9  int  9

=DeclareParameter  pt    int  1
=DeclareParameter  val   int  2

=DeclareParameter  Less    int  0
=DeclareParameter  Equal   int  1
=DeclareParameter  Greater int  2

== save the number of allocated data spaces
=Reset
=AllocSaveNum   3
=AllocSaveBytes 1

== Start counting passages
=CounterStart

== Construct empty pointed string
=NewEmptyPtString   Str1
=GetLength          Str1  pt  0
=GetString          Str1  pt  ""
=VerifyString       Str1  pt .true
=DestroyString      Str1

== Stop counting
=CounterStop

== verify memory leak
=Reset
=AllocCompareBytes 1
=AllocCompareNum   3
