// Script:    Tst-exc-01.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test exception handler

== Declarations
=DeclareParameter  idAssert     int    154
=DeclareParameter  idEnforce    int    153
=DeclareParameter  typeAssert   int      1
=DeclareParameter  typeEnforce  int      2
=DeclareParameter  typeError    int      3
=DeclareParameter  typePlatform int      4
=DeclareParameter  typeFailure  int      5

== Reset
=Reset
=AllocSaveNum   3
=AllocSaveBytes 1

== Test throwing assertion exception
=ThrowException    typeAssert   1   2  

== Test throwing enforce exception
=ThrowException    typeEnforce  4   5  

== Test throwing error exception
=ThrowException    typeError    7   8  

== Test throwing platform exception
=ThrowException    typePlatform   12  13  

== Test throwing failure exception
=ThrowException    typeFailure 10  11  

== Set the throw tracer on
=StartThrowTracing
=ThrowException    typeError    7   8  

== Test throwing enforce exception
=ThrowException    typeEnforce  4   5  

== Set the throw tracer off
=StopThrowTracing
=ThrowException    typeError    7   8  

== Test throwing failure exception
=ThrowException    typeFailure 10  11  

== Create an error message
=MakeError         0  "Usage error exception"  -1  111

== Display several versions
=DisplayException  0  0  
=DisplayException  0  1  
=DisplayException  0  2  

== Log the error
=LogException      0


== verify memory leak
=Reset
=AllocCompareNum   3
=AllocCompareBytes 1

//
// ==========>>> Must display test OK
//



