// Script:    Tst-main-04.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality

// Test throw, incorrectly catch due to exception type error

// Must cancel and display 4 errors, caused by an unrecovered exception 

//
// ==========>>> Must stop with 5 errors and disaster
//

== Declarations
=DeclareParameter  idAssert     int    154
=DeclareParameter  idEnforce    int    153
=DeclareParameter  typeAssert   int      1
=DeclareParameter  typeEnforce  int      2
=DeclareParameter  typeError    int      3
=DeclareParameter  typePlatform int      4
=DeclareParameter  typeFailure  int      5
=DeclareParameter  tstMessage   int   30147

=DeclareParameter  selectError   int     1
=DeclareParameter  selectFailure int     2

== Test incorrect exception catcher, wrong message id
=Throw              selectError  11  12  "test"
=ExceptionProgram   typeError    123 
// Should never reach this point

