// Script:    Tst-rnd-01.script
// Autor:     Arndt von Staa
// Data:      16/feb/2007
// Propósito: Test random number generator
//

== Start measuring time
=StartClock  1

== Display a uniform distribution of 2 elements [ 0 .. 1 ] generating 1.000 numbers
=newseed        0
=uniformdist    1000   0   1   0.022  0.1

== Display uniform distribution of 10 elements [ 1 .. 10 ] generating 1.000 numbers
=uniformdist     1000   1  10   0.03  0.1

== Display uniform distribution of 2 elements [ 5 .. 6 ] generating 100 numbers
=uniformdist       100   5   6   0.04  0.1

== Display uniform distribution of 50 numbers [ 0 .. 49 ] generating 1.000 numbers
=uniformdist     1000   0  49   0.03  0.1

== Display uniform distribution of 50 numbers [ 0 .. 49 ] generating 1.000.000 numbers
=newseed             0
=uniformdist  1000000   0  49   0.00088 0.00001

== Display uniform distribution of 50 numbers [ 0 .. 49 ] generating 1000 numbers, seed PI + time
=newseed            1
=uniformdist  1000000   0  49   0.001 0.001

== Display uniform distribution of 50 numbers [ 0 .. 49 ] generating 1000 numbers, given seed
=newseed      12345678
=uniformdist  1000000   0  49   0.00081 0.00001

== Test a large uniform distribution
=newseed            1
=largeUniform  10000000   0  40000    0.00035  0.0001

== Test a large uniform distribution generating zeroes
=newseed            0
=largeUniform    1000   0  250    0.1  0.1
=Recover

== Display frequency table [ 0 , 100 ] with 50% e 50%
=newseed        0
=frequencydist   1000 100  50 -1

== Display frequency table 1% 49% 49% 1% using variable seed
=newseed        1
=frequencydist   1000000 100  1  49  99 -1

== Display frequency table 1% 98% 1%   generate 1.000 numbers
=newseed        1
=frequencydist      100000 100 1 98  -1

== Display frequency table 1% 99%    generate 1.000 numbers
=newseed        1
=frequencydist      100000 100 1  -1

== Display frequency table 10% 20% 30% and 40%
=frequencydist   1000 100  10  30  60 -1

== Display frequency table 10% 20% 30% and 40% using seed = PI
=newseed        0
=frequencydist   1000000 100  10  30  60 -1

== Display frequency table 10% 20% 30% and 40% using seed time
=newseed        1
=frequencydist   1000000 100  10  30  60 -1

== Display frequency table 10% 20% 30% and 40% using given seed
=newseed        12345678
=frequencydist   1000000 100  10  30  60 -1

== Display frequency table 10% 20% 30% and 40% using given seed
=newseed        1
=frequencydist   10000 100  1  30  60 -1

== Display frequency table 98% 2%   generate 1.000 numbers
=frequencydist      1000 100  98  -1

== Display frequency table 98% 2%   generate 1.000.000 numbers
=frequencydist   1000000 100  98  -1

== Display frequency table 99,8% 0,2%   generate 1.000 numbers
=frequencydist      1000 1000 998  -1

== Display frequency table 99,8% 0,2%   generate 1.000.000 numbers
=frequencydist   1000000 1000 998  -1

== Display frequency table 0% 100% 0%   generate 100 numbers
=frequencydist   100 100   0 100 -1
=frequencydist   100 100   0     -1
=frequencydist   100 100 100     -1

== Display permutation of 20 elements
=permutation      1   20 

== Display permutation of 52 elements
=permutation      1   52 

== Display permutation of 10 elements
=newseed        1
=permutation    10   10 

== Display elapsed time
=DisplayElapsedTime  1

// fim
