// Script:    Tst-sls-01.script
// Author:    Arndt von Staa
// Date:      29/mai/2014
// Purpose:   Random symbol table test

== Reset all spaces
=reset

== Preserve the number of allocated spaces
=AllocSaveNum     1
=AllocSaveBytes   1

== Generate and test 
=GenerateTest    .true
+Control         23  40  4  1
+Generate      1000  100
+ActionDistrib  100    0    0    // 30  40  30 
+SizeDistrib     25   7 
+SizeDistrib     25  17
+SizeDistrib     25  21
+SizeDistrib     25  31
+ParameterListEnd

== Generate and test 
=GenerateTest    .true
+Control         31 100  2  1
+Generate      2000 100
+ActionDistrib   20  60  20 
+SizeDistrib     60  10 
+SizeDistrib     40  30
+ParameterListEnd

== Generate and test 
=GenerateTest    .true
+Control         31 100  2  1
+Generate      2000 100
+ActionDistrib  100   0  0   // 20  60  20 
+SizeDistrib     60  10 
+SizeDistrib     40  30
+ParameterListEnd



== Generate and test 
=GenerateTest    .true
+Control        503   999  2  1
+Generate      4500   50
+ActionDistrib  100 0  0    //  98   1   1 
+SizeDistrib     70  10 
+SizeDistrib     30  30
+ParameterListEnd

== Verify leakage
=reset
=AllocCompareNum   1
=AllocCompareBytes 1

