// Script:    Tst-str-01.script
// Author:    Arndt von Staa
// Date:      28/ago/2007
// Purpose:   Test string, converison to printable


DEPRECATED


== Declare constants
=DeclareParameter  Str1  int  1
=DeclareParameter  Str2  int  2
=DeclareParameter  Str3  int  3
=DeclareParameter  Str4  int  4
=DeclareParameter  Str9  int  9

=DeclareParameter  pt    int  1     // pointed to string
=DeclareParameter  val   int  2     // value string

=DeclareParameter  Less    int  0
=DeclareParameter  Equal   int  1
=DeclareParameter  Greater int  2

=DeclareParameter  AssertionExc      int 1
=DeclareParameter  EnforceExc        int 2
=DeclareParameter  ErrorExc          int 3
=DeclareParameter  FailureExc        int 4
=DeclareParameter  AssertionExcId    int 144

== save the number of allocated data spaces
=Reset
=AllocSaveNum   3
=AllocSaveBytes 1

== verify memory leak
=DestroyString      Str2
=Reset
=AllocCompareBytes 1
=AllocCompareNum   3
