// Script:    Tst-mut-02.script
// Author:    Arndt von Staa
// Date:      30/jun/2017
// Purpose:   Test counter, although the dummy is a mutation test tester

== Start measuring time
=StartClock  1

== Try to read non existing file

=CounterReadDeclaration   "..\\sources\\mut"
=Recover

== Read a counter file
=CounterReadDeclaration   "..\\sources\\mutant"
=CounterGetNum            13
=CounterStart

== Read again an existing file
=CounterReadDeclaration   "..\\sources\\mutant"
=Recover
=FailureReset             12

== Verify contents
=CounterGetNum            13
=CounterGetCount          "01 Start test"                         0
=CounterGetCount          "02 Fill prime array with garbage"      0
=CounterGetCount          "03 Do mutation 11"                     0
=CounterGetCount          "04 Do original 11"                     0
=CounterGetCount          "05 Set maxNum min"                    -2
=CounterGetCount          "06 Set maxNum max"                    -1
=CounterGetCount          "07 Generate number"                   -3
=CounterGetCount          "08 Test divisible by existing prime"   0
=CounterGetCount          "09 Found divisible by existing prime"  0
=CounterGetCount          "10 Register new prime"                 0
=CounterGetCount          "11 Do mutation 10"                     0
=CounterGetCount          "12 Do original 10"                     0
=CounterGetCount          "13 End"                                0

== Verify zero counters
=CounterVerifyZero        11
=FailureReset             11

== Count normal run
=SetIdMutant              0
=MutationTest             20  8

== List all counters
=CounterDisplay

== Verify all counters
=CounterGetCount          "01 Start test"                         1
=CounterGetCount          "02 Fill prime array with garbage"    197
=CounterGetCount          "03 Do mutation 11"                     0
=CounterGetCount          "04 Do original 11"                     1
=CounterGetCount          "05 Set maxNum min"                    -2
=CounterGetCount          "06 Set maxNum max"                    -1
=CounterGetCount          "07 Generate number"                    7
=CounterGetCount          "08 Test divisible by existing prime"  29
=CounterGetCount          "09 Found divisible by existing prime"  2
=CounterGetCount          "10 Register new prime"                 5
=CounterGetCount          "11 Do mutation 10"                     0
=CounterGetCount          "12 Do original 10"                     5
=CounterGetCount          "13 End"                                1

== Verify how many counters are still zero
=CounterVerifyZero        2
=FailureReset             2

== Count with mutant 10
=SetIdMutant              10
=MutationTest             20  3

== List all counters
=CounterDisplay

== Verify all counters
=CounterGetCount          "01 Start test"                         2
=CounterGetCount          "02 Fill prime array with garbage"    394
=CounterGetCount          "03 Do mutation 11"                     0
=CounterGetCount          "04 Do original 11"                     2
=CounterGetCount          "05 Set maxNum min"                    -2
=CounterGetCount          "06 Set maxNum max"                    -1
=CounterGetCount          "07 Generate number"                   14
=CounterGetCount          "08 Test divisible by existing prime"  48
=CounterGetCount          "09 Found divisible by existing prime"  4
=CounterGetCount          "10 Register new prime"                10
=CounterGetCount          "11 Do mutation 10"                     5
=CounterGetCount          "12 Do original 10"                     5
=CounterGetCount          "13 End"                                2

== Verify how many counters are still zero
=CounterVerifyZero        1
=FailureReset             1

== Count with mutant 11
=SetIdMutant              11
=MutationTest             20  8

== List all counters
=CounterDisplay

== Verify all counters
=CounterGetCount          "01 Start test"                         3
=CounterGetCount          "02 Fill prime array with garbage"    591
=CounterGetCount          "03 Do mutation 11"                     1
=CounterGetCount          "04 Do original 11"                     2
=CounterGetCount          "05 Set maxNum min"                    -2
=CounterGetCount          "06 Set maxNum max"                    -1
=CounterGetCount          "07 Generate number"                   21
=CounterGetCount          "08 Test divisible by existing prime"  77
=CounterGetCount          "09 Found divisible by existing prime"  6
=CounterGetCount          "10 Register new prime"                15
=CounterGetCount          "11 Do mutation 10"                     5
=CounterGetCount          "12 Do original 10"                    10
=CounterGetCount          "13 End"                                3

== Verify how many counters are still zero
=CounterVerifyZero        0

== End measuring time
=Reset
=DisplayElapsedTime      1
